# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1603, 1158)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.video_title = QtWidgets.QLabel(self.centralwidget)
        self.video_title.setStyleSheet("font: 75 11pt \"Adobe Devanagari\";")
        self.video_title.setObjectName("video_title")
        self.gridLayout.addWidget(self.video_title, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_FrameViewer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_FrameViewer.sizePolicy().hasHeightForWidth())
        self.tab_FrameViewer.setSizePolicy(sizePolicy)
        self.tab_FrameViewer.setObjectName("tab_FrameViewer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_FrameViewer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.tab_FrameViewer)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 0, 1, 1, 2)
        self.label_frameNum = QtWidgets.QLabel(self.frame_2)
        self.label_frameNum.setStyleSheet("font: 75 9pt \"Adobe Devanagari\";")
        self.label_frameNum.setObjectName("label_frameNum")
        self.gridLayout_3.addWidget(self.label_frameNum, 2, 1, 1, 2, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.L_button = QtWidgets.QPushButton(self.frame_2)
        self.L_button.setMinimumSize(QtCore.QSize(100, 100))
        self.L_button.setMaximumSize(QtCore.QSize(100, 100))
        self.L_button.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.L_button.setObjectName("L_button")
        self.gridLayout_3.addWidget(self.L_button, 1, 1, 1, 1)
        self.R_button = QtWidgets.QPushButton(self.frame_2)
        self.R_button.setMinimumSize(QtCore.QSize(100, 100))
        self.R_button.setMaximumSize(QtCore.QSize(100, 100))
        self.R_button.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.R_button.setObjectName("R_button")
        self.gridLayout_3.addWidget(self.R_button, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_2.addWidget(self.frame, 2, 1, 1, 1)
        self.checkBox_StoreData = QtWidgets.QCheckBox(self.tab_FrameViewer)
        self.checkBox_StoreData.setObjectName("checkBox_StoreData")
        self.gridLayout_2.addWidget(self.checkBox_StoreData, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        
        #self.graphicsView = PlotWidget(self.tab_FrameViewer)
        #self.graphicsView.setObjectName("graphicsView")
        #self.graphicsView.setAspectLocked(True) #keeps aspect locked for imported video frames, otherwise it stretches everything out.        
        
    
        self.graphicsView = PlotWidget(self.tab_FrameViewer)
        
        
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.setAspectLocked(True) #keeps aspect locked for imported video frames, otherwise it stretches everything out.        
        
        
        self.gridLayout_2.addWidget(self.graphicsView, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_FrameViewer, "")
        self.tab_Data = QtWidgets.QWidget()
        self.tab_Data.setObjectName("tab_Data")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_Data)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView_Plot = QtWidgets.QGraphicsView(self.tab_Data)
        self.graphicsView_Plot.setObjectName("graphicsView_Plot")
        #sizePolicy.setHeightForWidth(self.graphicsView_Plot.sizeAdjustPolicy())        
        self.horizontalLayout_2.addWidget(self.graphicsView_Plot)
        self.dataDisplay = QtWidgets.QTextBrowser(self.tab_Data)
        self.dataDisplay.setMaximumSize(QtCore.QSize(640, 16777215))
        self.dataDisplay.setObjectName("dataDisplay")
        self.horizontalLayout_2.addWidget(self.dataDisplay)
        self.tabWidget.addTab(self.tab_Data, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1603, 47))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuAutomation_Levels = QtWidgets.QMenu(self.menuOptions)
        self.menuAutomation_Levels.setObjectName("menuAutomation_Levels")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpload_new = QtWidgets.QAction(MainWindow)
        self.actionUpload_new.setObjectName("actionUpload_new")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionPupil_detection_assist = QtWidgets.QAction(MainWindow)
        self.actionPupil_detection_assist.setCheckable(True)
        self.actionPupil_detection_assist.setChecked(False)
        self.actionPupil_detection_assist.setObjectName("actionPupil_detection_assist")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setObjectName("actionProperties")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionImage_shift_detection = QtWidgets.QAction(MainWindow)
        self.actionImage_shift_detection.setObjectName("actionImage_shift_detection")
        self.action1_No_assistance = QtWidgets.QAction(MainWindow)
        self.action1_No_assistance.setCheckable(True)
        self.action1_No_assistance.setObjectName("action1_No_assistance")
        self.action2_carryoverselection = QtWidgets.QAction(MainWindow)
        self.action2_carryoverselection.setCheckable(True)
        self.action2_carryoverselection.setChecked(True)
        self.action2_carryoverselection.setObjectName("action2_carryoverselection")
        self.action3_Carry_over_selection_image_shift_detection = QtWidgets.QAction(MainWindow)
        self.action3_Carry_over_selection_image_shift_detection.setCheckable(True)
        self.action3_Carry_over_selection_image_shift_detection.setObjectName("action3_Carry_over_selection_image_shift_detection")
        self.action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment = QtWidgets.QAction(MainWindow)
        self.action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment.setCheckable(True)
        self.action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment.setObjectName("action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment")
        self.action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only = QtWidgets.QAction(MainWindow)
        self.action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only.setCheckable(True)
        self.action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only.setObjectName("action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only")
        self.menuFile.addAction(self.actionUpload_new)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuAutomation_Levels.addAction(self.action1_No_assistance)
        self.menuAutomation_Levels.addAction(self.action2_carryoverselection)
        self.menuAutomation_Levels.addAction(self.action3_Carry_over_selection_image_shift_detection)
        self.menuAutomation_Levels.addAction(self.action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment)
        self.menuAutomation_Levels.addAction(self.action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only)
        self.menuOptions.addAction(self.menuAutomation_Levels.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionProperties)
        self.menuHelp.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video_title.setText(_translate("MainWindow", "VIDEO TITLE"))
        self.label_frameNum.setText(_translate("MainWindow", "FRAME_NUM"))
        self.L_button.setText(_translate("MainWindow", "🡰"))
        self.R_button.setText(_translate("MainWindow", "🡲"))
        self.checkBox_StoreData.setText(_translate("MainWindow", "Store data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_FrameViewer), _translate("MainWindow", "Frame Viewer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Data), _translate("MainWindow", "Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuAutomation_Levels.setTitle(_translate("MainWindow", "Automation Levels"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUpload_new.setText(_translate("MainWindow", "Upload new"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionPupil_detection_assist.setText(_translate("MainWindow", "Pupil detection assist"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionImage_shift_detection.setText(_translate("MainWindow", "Image shift detection"))
        self.action1_No_assistance.setText(_translate("MainWindow", "1 - No assistance"))
        self.action2_carryoverselection.setText(_translate("MainWindow", "2 - Carry over selection"))
        self.action3_Carry_over_selection_image_shift_detection.setText(_translate("MainWindow", "3 - Carry over selection, image shift detection"))
        self.action4_Carry_over_selection_image_shift_detection_pupil_size_adjustment.setText(_translate("MainWindow", "4 - Carry over selection, image shift detection, pupil size adjustment"))
        self.action5_Automated_pupil_detection_indicate_pupil_on_first_frame_only.setText(_translate("MainWindow", "5 - Automated pupil detection (indicate pupil on first frame only) "))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

